// packages/react-app/src/App.js
import React from 'react'
import './App.css'

function App() {
  return (
    <div className="App">
      <cmp-button onClick={onClick}>Default button</cmp-button>
      <cmp-button primary onClick={onClickPrimary}>
        Primary button
      </cmp-button>
      <cmp-button secondary onClick={onClickSecondary}>
        Secondary button
      </cmp-button>
    </div>
  )
}

function onClick() {
  console.log('click on button')
}

function onClickPrimary() {
  console.log('click on primary button')
}

function onClickSecondary() {
  console.log('click on secondary button')
}

export default App

// packages/angular-app/src/app/app.component.ts
import { Component } from '@angular/core'

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.scss']
})
export class AppComponent {
  title = 'angular-app'

  onClick() {
    console.log('click on button')
  }

  onClickPrimary() {
    console.log('click on primary button')
  }

  onClickSecondary() {
    console.log('click on secondary button')
  }
}

<!--The content below is only a placeholder and can be replaced.-->
<div style="text-align:center">
  <h1>Welcome to {{ title }}!</h1>
  <cmp-button (click)="onClick()">Default button</cmp-button>
  <cmp-button primary (click)="onClickPrimary()">
    Primary button
  </cmp-button>
  <cmp-button secondary (click)="onClickSecondary()">
    Secondary button
  </cmp-button>
</div>

<router-outlet></router-outlet>
